# Generated by Django 4.2 on 2024-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_otptoken_otp_code_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a7d888', max_length=6),
        ),
    ]
