# Generated by Django 4.2 on 2024-06-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='busID',
        ),
        migrations.AlterField(
            model_name='bus',
            name='busNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='871fec', max_length=6),
        ),
    ]
