# Generated by Django 4.2 on 2024-06-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_bus_busid_alter_bus_busnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communication',
            name='communicationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerservicerequest',
            name='requestID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='443f84', max_length=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='realtimeupdates',
            name='updateID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='routeID',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduleID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='userNotificationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
