# Generated by Django 4.2 on 2024-06-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_otptoken_otp_code_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='bus',
            new_name='busInfo',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0a0d16', max_length=6),
        ),
    ]
