# Generated by Django 4.2 on 2024-06-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='busInfo',
            new_name='bus',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seatNumber',
            new_name='seat_number',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='54e7fc', max_length=6),
        ),
    ]
