# Generated by Django 4.2 on 2024-06-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seatNumber',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='main.seat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='d5998e', max_length=6),
        ),
    ]
