# Generated by Django 4.2 on 2024-06-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_booking_seatnumber_booking_seat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seatNumber',
            field=models.CharField(default=7, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='9bf373', max_length=6),
        ),
    ]
