# Generated by Django 4.2 on 2024-07-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_booking_status_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seatNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='ced7c9', max_length=6),
        ),
    ]
