# Generated by Django 4.2 on 2024-07-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_otptoken_otp_code_alter_profile_phone_number'),
        ('main', '0026_profile_gender_alter_otptoken_otp_code'),
    ]

    operations = [
    ]
