# Generated by Django 4.2 on 2024-07-12 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.booking'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='f1f2ee', max_length=6),
        ),
    ]
